from .AnosLectivos import AnoLectivo
from .Calificaciones import Calificacion
from .Estudiantes import Estudiante
from .Grados import Grado
from .Materias import Materia
from .MateriaSeccion import MateriaSeccion
from .matriculas import Matricula
from .Periodos import Periodo
from .Promedios_anuales import PromedioAnual
from .Promedios_periodo import PromedioPeriodo
from .roles import Rol
from .Secciones import Seccion
from .usuarios import Usuario
from .Inasistencias import Inasistencia
